
<div class="widget grid12">
    <div class="whead"><h6>Nueva Imagen</h6>
        <div class="clear"></div>

    </div>

    <div class="formRow fluid">
      <?php echo $this->form?>
    </div>

</div>


    

    <?php if (!empty($this->banner)): ?>
        <div class="widget check grid9">
            <div class="whead">
                <span class="titleIcon"><input type="checkbox" id="titleCheck" name="titleCheck" /></span>
                <h6>Media table</h6><div class="clear"></div>
            </div>
            <table cellpadding="0" cellspacing="0" width="100%" class="tDefault checkAll tMedia" id="checkAll">
                <thead>
                    <tr>
                        <td><img src="<?php echo STATIC_ADMIN_IMG; ?>/elements/other/tableArrows.png" alt="" /></td>
                        <td width="50">Imagen</td>
                        <td class="sortCol"><div>Descripción<span></span></div></td>
                        <td width="130" class="sortCol"><div>Fecha<span></span></div></td>
                        <td width="120">File info</td>
                        <td width="100">Acciones</td>
                    </tr>
                </thead>
                <tfoot>
                    <tr>
                        <td colspan="6">
                            <div class="itemActions">
                                <label>Seleccion:</label>
                                <select>
                                    <option value="">Select action...</option>
                                    <option value="Edit">Editar</option>
                                    <option value="Delete">Borrar</option>
                                    <option value="Move">Desactivar</option>
                                </select>
                            </div>
                            <div class="tPages">
                                <!--                                <ul class="pages">
                                                                    <li class="prev"><a href="#" title=""><span class="icon-arrow-14"></span></a></li>
                                                                    <li><a href="#" title="" class="active">1</a></li>
                                                                    <li><a href="#" title="">2</a></li>
                                                                    <li><a href="#" title="">3</a></li>
                                                                    <li><a href="#" title="">4</a></li>
                                                                    <li>...</li>
                                                                    <li><a href="#" title="">20</a></li>
                                                                    <li class="next"><a href="#" title=""><span class="icon-arrow-17"></span></a></li>
                                                                </ul>-->
                            </div>
                        </td>
                    </tr>
                </tfoot>
                <tbody>
                    <?php foreach ($this->banner as
                            $index): ?>
                        <tr>
                            <td><input type="checkbox" name="checkRow" /></td>
                            <td>
                                <a href="<?php echo DINAMIC_URL; ?>/banner/<?php echo $index['banner_img'] ?>" title="" class="lightbox">
                                    <img src="<?php echo DINAMIC_URL; ?>/banner/<?php echo $index['banner_img'] ?>" 
                                         alt="" width="57" height="36"/>
                                </a>
                            </td>
                            <td class="textL">
                                <a href="#" title=""><?php echo $index['banner_nombre'] ?></a>
                            </td>
                            <td><?php echo date('d-m-Y') ?></td>
                            <td class="fileInfo">
                                <span>
                                    <strong>Size:</strong> 215 Kb</span>
                                <span><strong>Format:</strong> .jpg</span>
                            </td>
                            <td class="tableActs">
                                <a href="#" class="tablectrl_small bDefault tipS" title="Editar">
                                    <span class="iconb" data-icon="&#xe1db;"></span></a>
                                <a href="#" class="tablectrl_small bDefault tipS" title="Borrar">
                                    <span class="iconb" data-icon="&#xe136;"></span></a>
                                <a href="#" class="tablectrl_small bDefault tipS" title="Desactivar">
                                    <span class="iconb" data-icon="&#xe1f7;"></span></a>
                            </td>
                        </tr>
                    <?php endforeach ?>
                </tbody>
            </table>
        </div>
    </div>
<?php endif; ?>
