<br>
    <a href="#" class="buttonM bDefault ml10" 
       id="formDialog_open">
        Nuevo Tipo de Colaboración
    </a>
<?php if (!empty($this->listaTipoColaboracion)): ?>
    <div class="widget check grid9">
        <div class="whead">
            <span class="titleIcon">
                <input type="checkbox"  id="titleCheck" name="titleCheck" />
            </span>
            <h6>Tipos de colaboración del Home</h6>
            <div class="clear"></div>
        </div>
        <table cellpadding="0" cellspacing="0" width="100%" class="tDefault checkAll tMedia" id="checkAll">
            <thead>
                <tr>
                    <td>
                        Home
                    </td>
                    <td width="50">Imagen</td>
                    <td width="130">Nombre</td>
                    <td class="sortCol">
                        <div>Titulo<span>
                                
                            </span></div>
                    </td>
                    <td width="130" class="sortCol"><div>Fecha<span></span></div></td>                        
                    <td width="100">Acciones</td>
                </tr>
            </thead>
            <tfoot>
                <tr>
                    <td colspan="6">
                        <div class="itemActions">
                            <label>Seleccion:</label>
                            <select>
                                <option value="">Select action...</option>
                                <option value="Edit">Editar</option>
                                <option value="Delete">Borrar</option>
                                <option value="Move">Desactivar</option>
                            </select>
                        </div>
                        <div class="tPages">
                            <!--                                <ul class="pages">
                                                                <li class="prev"><a href="#" title=""><span class="icon-arrow-14"></span></a></li>
                                                                <li><a href="#" title="" class="active">1</a></li>
                                                                <li><a href="#" title="">2</a></li>
                                                                <li><a href="#" title="">3</a></li>
                                                                <li><a href="#" title="">4</a></li>
                                                                <li>...</li>
                                                                <li><a href="#" title="">20</a></li>
                                                                <li class="next"><a href="#" title=""><span class="icon-arrow-17"></span></a></li>
                                                            </ul>-->
                        </div>
                    </td>
                </tr>
            </tfoot>
            <tbody>
                <?php foreach ($this->$this->listaTipoColaboracion as  $index): ?>
                    <tr>
                        <td>
                            <input type="checkbox" 
                                   name="checkRow" 
                                   <?if($index['noticias_home']==1):?>
                                   checked="checked"
                                   <?php endif;?>/>
                        </td>
                        <td>
                            <a href="<?php echo DINAMIC_URL; ?>/colabora/images/<?php                             
                            echo $index['tipo_colaboracion_img']?>" 
                               title="" 
                               class="lightbox">
                            <img src="<?php echo DINAMIC_URL; ?>/colabora/images/<?php                            
                            echo $index['tipo_colaboracion_img']?>" 
                               alt="" width="57" height="36"/>
                            </a>
                        </td>
                        <td>                   
                        <?php echo $index['tipo_colaboracion_titulo'] ?>
                                        </td>
                         <td class="textL">
                        <?php echo $index['noticias_descripcion_corta']. '....' ?>
                        </td>
                        <td><?php echo $index['fecha_creacion'] ?></td>                            
                        <td class="tableActs">
                            <a href="/admin/home/delete-notice/id/<?php echo $index['noticias_id'] ?>" 
                               class="tablectrl_small bDefault tipS" 
                               title="Borrar Noticia">
                                <span class="iconb" data-icon="&#xe136;"></span>
                            </a>
                            <?php $action=($index['noticias_home']=='')?
                                'publish-home-notice':'unpublish-home-notice';?>
                            <a href="/admin/home/<?php echo $action?>/id/<?php                             
                            echo $index['noticias_id'] ?>" 
                                   class="tablectrl_small bDefault tipS" 
                                   title="<?php echo $index['noticias_home']==0 ?
                                        'Publicar Home' : 'retirar home'?>">
                                    <span class="iconb" data-icon="&#xe1f7;">
                                        
                                    </span>
                           </a>
                        </td>
                    </tr>
    <?php endforeach ?>
            </tbody>
        </table>
    </div>
    </div>
<?php endif; ?>
<div id="formDialog" class="dialog" title="Ingrese nuevo Noticia">
<?php echo $this->form?>
</div>