<div class="nNote"><?php foreach($this->message as $index):  
echo '<p>'.$index.'</p>';
 endforeach;  ?></div>
<a href="/admin/imagenes/insert">Nuevo Registro</a>
<table>
    <tr> 
        <td>nombre </td>
        <td>descripcion</td>
        <td>imagen</td>
        <td>estado</td>
        <td>orden</td>
        <td>Opciones</td>
    </tr>
    
 <?php 
 $arrayEstado = array('no publico', 'publico' );
 $arrayLinkPublicar = array(
     array('link'=>'/admin/imagenes/publicar/id/','label'=>'publicar'), 
     array('link'=>'/admin/imagenes/despublicar/id/','label'=>'despublicar'), 
     );
 foreach($this->listingImagenes as $index): ?>
    <tr> 
        <td><?php echo $index['imagenes_nombre']; ?></td>
        <td><?php echo $index['imagenes_descripcion']; ?></td>
        <td><?php echo $index['imagenes_imagen']; ?></td>
        <td><?php echo $arrayEstado[$index['imagenes_publico']]; ?></td>
        <td><?php echo $index['imagenes_orden']; ?></td>
        <td>
            <a href="/admin/imagenes/edit/id/<?php echo $index['imagenes_id']; ?>" > [Editar]</a>
            <a href="<?php echo $arrayLinkPublicar[$index['imagenes_publico']]['link'].$index['imagenes_id']; ?>">[<?php echo $arrayLinkPublicar[$index['imagenes_publico']]['label']; ?>]</a>
            <a href="/admin/imagenes/uporder/id/<?php echo $index['imagenes_id']; ?>" > [Subir orden]</a>
            <a href="/admin/imagenes/lowerorder/id/<?php echo $index['imagenes_id']; ?>" > [Bajar orden]</a>
        </td>
    </tr>

<?php endforeach; ?>
</table>