<?php $this->doctype() ?>

<html xmlns="http://www.w3.org/1999/xhtml" lang="es">
    <head>
        <?php $this->headTitle() ?>
        <?php $this->headMeta() ?>
        <?php $this->headLink() ?>
        <link href="<?php echo STATIC_URL; ?>/css/estilo.css" type="text/css" rel="stylesheet"/>
        <?php $this->headScript() ?>
        <?php $this->headStyle() ?>       
        <script src="<?php echo STATIC_URL; ?>/js/jquery-1.8.2.min.js" type="text/javascript"></script>
        <script src="<?php echo STATIC_URL; ?>/js/jquery.cycle.all.js" type="text/javascript"></script>

    </head>
    <body>
        <div class="body-container">
            <div class="header">
                <div class="logo"><img src="<?php echo STATIC_URL; ?>/images/logo.jpg" /></div>
                <ul class="topmenu">
                    <li><a href="#"><img src="<?php echo STATIC_URL; ?>/images/menu-lacompania.jpg"/></a></li>
                    <li><a href="#"><img src="<?php echo STATIC_URL; ?>/images/menu-nuestralabor.jpg"/></a></li>
                    <li><a href="#"><img src="<?php echo STATIC_URL; ?>/images/menu-colabora.jpg"/></a></li>
                    <li><a href="#"><img src="<?php echo STATIC_URL; ?>/images/menu-unete.jpg"/></a></li>
                    <li><a href="#"><img src="<?php echo STATIC_URL; ?>/images/menu-saladeprensa.jpg"/></a></li>
                    <li><a href="#"><img src="<?php echo STATIC_URL; ?>/images/menu-descarga.jpg"/></a></li>
                    <li><a href="#"><img src="<?php echo STATIC_URL; ?>/images/menu-voluntariado.jpg"/></a></li>
                </ul>
                <ul class="toplinks">
                    <li><a href="#">Inicio</a></li>
                    <li><a href="#">Favoritos</a></li>
                    <li><a href="#">Contactanos</a></li>
                    <li><a href="#">Mapa del sitio</a></li>
                </ul>
            </div>
            <?php if(!empty($this->banner)){ ?>
            <div class="slideshow-cont">
                <div class="slideshow" style="position: relative; width: 834px; height: 390px;">
                    <?php foreach($this->banner as $index): ?>
                    <a href="<?php echo $index['banner_link'];?>">
                        <img width="834" height="390" src="<?php echo DINAMIC_URL; ?>/banner/<?php echo $index['banner_img'] ?>" style="position: absolute; top: 0px; left: 0px; z-index: 8; opacity: 1; height: 390px; width: 834px;"/>
                    </a>
                    
                    <?php endforeach;?>
<!--                    
                    <img width="834" height="390" src="<?php echo STATIC_URL; ?>/images/001.jpg" style="position: absolute; top: 0px; left: 0px; z-index: 8; opacity: 0; height: 390px; width: 834px; display: none;"/>
                    <img width="834" height="390" src="<?php echo STATIC_URL; ?>/images/002.jpg" style="position: absolute; top: 0px; left: 0px; display: none; z-index: 8; height: 390px; opacity: 0; width: 834px;"/>
                    <img width="834" height="390" src="<?php echo STATIC_URL; ?>/images/003.jpg" style="position: absolute; top: 0px; left: 0px; display: block; z-index: 9; height: 390px; opacity: 1; width: 834px;"/>
                    <img width="834" height="390" src="<?php echo STATIC_URL; ?>/images/004.jpg" style="position: absolute; top: 0px; left: 0px; display: none; z-index: 8; height: 390px; opacity: 0; width: 834px;"/>
                    <img width="834" height="390" src="<?php echo STATIC_URL; ?>/images/005.jpg" style="position: absolute; top: 0px; left: 0px; display: none; z-index: 8; height: 390px; opacity: 0; width: 834px;"/>
                    <img width="834" height="390" src="<?php echo STATIC_URL; ?>/images/006.jpg" style="position: absolute; top: 0px; left: 0px; display: none; z-index: 8; height: 390px; opacity: 0; width: 834px;"/>
                    <img width="834" height="390" src="<?php echo STATIC_URL; ?>/images/007.jpg" style="position: absolute; top: 0px; left: 0px; display: none; z-index: 8; height: 390px; opacity: 0; width: 834px;"/>
                    <img width="834" height="390" src="<?php echo STATIC_URL; ?>/images/008.jpg" style="position: absolute; top: 0px; left: 0px; display: none; z-index: 8; height: 390px; opacity: 0; width: 834px;"/>-->
                </div>
            </div>
            <?php } else{ ?>
            <div class="breadcrumb"><a href="#">Inicio</a> &gt; <a href="#">Inicio</a></div>
            <?php }  ?>
            <div class="bottom-content">
                <?php echo $this->layout()->content ?>
            </div>
            <div class="footer">
                <div class="leftside">
                    <h1 class="section-title">MAPA GENERAL</h1>
                    <ul class="bottom_menu">
                        <li><a href="#">La compania</a></li>
                        <li><a href="#">La compania</a></li>
                        <li><a href="#">La compania</a></li>
                        <li><a href="#">La compania</a></li>
                        <li><a href="#">La compania</a></li>
                        <li><a href="#">La compania</a></li>
                        <li><a href="#">La compania</a></li>
                        <li><a href="#">La compania</a></li>
                    </ul>
                </div>
                <div class="rightside">
                    <h1 class="section-title">Estamos en las Redes Sociales</h1>
                    <a href="#"><img src="<?php echo STATIC_URL; ?>/images/logoicon.jpg"/></a>
                    <a href="#"><img src="<?php echo STATIC_URL; ?>/images/logoicon.jpg"/></a>
                    <a href="#"><img src="<?php echo STATIC_URL; ?>/images/logoicon.jpg"/></a>
                    <a href="#"><img src="<?php echo STATIC_URL; ?>/images/logoicon.jpg"/></a>
                </div>
                <div class="footer-wide">Lorem ipsum <br> lorem ipsum</div>
            </div>
        </div>

    </body>





</html>