<?php $this->doctype() ?>

<html xmlns="http://www.w3.org/1999/xhtml" lang="es">
    <head>
        <?php $this->headTitle() ?>
        <?php $this->headMeta() ?>
        <?php $this->headLink() ?>
        <?php $this->headScript() ?>
        <?php $this->headStyle() ?>       
    </head>
    <body>
      
        <div id="container">
          
                <?php $this->layout()->content ?>
           
        </div>        
        
    </body>
</html>