<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"><head>
        <meta http-equiv="Content-type" content="text/html;charset=UTF-8">
        <?php $this->headTitle() ?>
        <?php $this->headMeta() ?>
        <?php $this->headLink() ?>

        <?php $this->headScript() ?>
        <?php $this->headStyle() ?> 

              
        <script src="<?php echo STATIC_URL; ?>/js/jquery-1.8.2.min.js" type="text/javascript"></script>
        <script src="<?php echo STATIC_URL; ?>/js/jquery.cycle.all.js" type="text/javascript"></script>
        <script type="text/javascript">
            $(function() {
                $('.slideshow').cycle({
                    fx:     'fade',
                    speed:  'fast',
                    timeout: 3000,
                    pager:  '#nav',
                    slideExpr: 'img'
                });
            });
        </script>
        <link href="<?php echo STATIC_URL; ?>/css/fontface.css?ver=<?php echo rand(1, 500); ?>" type="text/css" rel="stylesheet"/>
        <link href="<?php echo STATIC_URL; ?>/css/estilo.css?ver=<?php echo rand(1, 500); ?>" type="text/css" rel="stylesheet"/>
    </head>
    <body>
        <div class="body-container">
            <div class="header">
                <div class="logo"><a href="/"><img src="<?php echo STATIC_URL; ?>/images/logo.png" alt="Global Humanitaria Perú"></a></div>
                <?php 
                
                //print_r(Zend_Registry::get('navigationMais'));
                echo $this->navigation()->menu()->renderMenu(Zend_Registry::get('navigationMais'),array('ulClass'=>'topmenu')); ?>
<!--                <ul class="topmenu">
                    <li class="first"><a href="/quienes-somos"><span>¿QUIÉNES SOMOS?</span></a></li>
                    <li><a href="nuestra-labor.html"><span>NUESTRA LABOR</span></a></li>
                    <li><a href="colabora.html"><span>COLABORA</span></a></li>
                    <li><a href="unete.html"><span>ÚNETE</span></a></li>
                    <li><a href="sala-de-prensa.html"><span>SALA DE PRENSA	</span></a></li>
                    <li><a href="descarga.html"><span>DESCARGA</span></a></li>
                    <li><a href="voluntariado.html"><span>VOLUNTARIADO</span></a></li>
                </ul>-->
                <ul class="toplinks">
                    <li><a class="active inicio" href="#">Inicio</a></li>
                    <li><a class="favoritos" href="#">Favoritos</a></li>
                    <li><a class="contactenos" href="#">Contactanos</a></li>
                    <li><a class="mapadelsitio" href="#">Mapa del sitio</a></li>
                </ul>
            </div>
            <?php if (!empty($this->banner)) { ?>
                <div class="slideshow-cont">
                    <div class="slideshow-control">
                        <div class="nextprev-controls">
                            <a href="#" class="prevlink"><span id="prev">Prev</span></a> 
                            <a href="#" class="nextlink"><span id="next">Next</span></a>
                        </div>
                        <ul id="nav"></ul>
                    </div>
                    <div class="slideshow" style="position: relative; width: 834px; height: 390px;">
                        <?php foreach ($this->banner as $index): ?>

                            <img width="834" height="390" src="<?php echo DINAMIC_URL; ?>/banner/<?php echo $index['banner_img'] ?>" />

                        <?php endforeach; ?>
                    </div>
                </div>
            <?php } else { ?>
<!--                <div class="breadcrumb"><a href="#">Inicio</a> &gt; <a href="#">Inicio</a></div>-->
            <?php } ?>
            <div class="bottom-content">
                <?php echo $this->layout()->content ?>
            </div>
            <div class="footer">
                <div class="leftside">
                    <h1 class="section-title">MAPA GENERAL</h1>
                    <ul class="bottom_menu">
                        <li><a href="quienes-somos">Quienes somos</a></li>
                        <li><a href="unete">&Uacute;nete</a></li>
                        <li><a href="voluntariado">Voluntariado</a></li>
                        <li><a href="nuestra-labor">Nuestra labor</a></li>
                        <li><a href="sala-de-prensa">Sala de prensa</a></li>
                        <li><a href="contactanos">Cont&aacute;ctanos</a></li>
                        <li><a href="colabora">Colabora</a></li>
                        <li><a href="descarga">Descargas</a></li>
                      </ul>
                </div>
                <div class="rightside">
                    <h1 class="section-title">Estamos en las Redes Sociales</h1>
                    <a href="#"><img src="<?php echo STATIC_URL; ?>/images/facebook.png" alt="Facebook"></a>
                    <a href="#"><img src="<?php echo STATIC_URL; ?>/images/twitter.png" alt="Twitter"></a>
                    <a href="#"><img src="<?php echo STATIC_URL; ?>/images/flickr.png" alt="Flickr"></a>
                    <a href="#"><img src="<?php echo STATIC_URL; ?>/images/youtube.png" alt="Youtube"></a>
                </div>
                <div class="footer-wide">&reg; Global Humanitaria 2012 todos los derechos reservados<br>Creado y desarrollado por Crystal Studio </div>
            </div>
        </div>

    </body>
</html>