<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0" />
<title>Aquincum - premium admin template by Eugene Kopyov</title>

<link href="<?php echo STATIC_URL; ?>/css-admin/styles.css" rel="stylesheet" type="text/css" />
<!--[if IE]> <link href="css/ie.css" rel="stylesheet" type="text/css"> <![endif]-->

<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.7/jquery.min.js"></script>

<script type="text/javascript" src="<?php echo STATIC_URL; ?>/js-admin/plugins/forms/ui.spinner.js"></script>
<script type="text/javascript" src="<?php echo STATIC_URL; ?>/js-admin/plugins/forms/jquery.mousewheel.js"></script>
 
<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8/jquery-ui.min.js"></script>

<script type="text/javascript" src="<?php echo STATIC_URL; ?>/js-admin/plugins/charts/excanvas.min.js"></script>
<script type="text/javascript" src="<?php echo STATIC_URL; ?>/js-admin/plugins/charts/jquery.flot.js"></script>
<script type="text/javascript" src="<?php echo STATIC_URL; ?>/js-admin/plugins/charts/jquery.flot.orderBars.js"></script>
<script type="text/javascript" src="<?php echo STATIC_URL; ?>/js-admin/plugins/charts/jquery.flot.pie.js"></script>
<script type="text/javascript" src="<?php echo STATIC_URL; ?>/js-admin/plugins/charts/jquery.flot.resize.js"></script>
<script type="text/javascript" src="<?php echo STATIC_URL; ?>/js-admin/plugins/charts/jquery.sparkline.min.js"></script>

<script type="text/javascript" src="<?php echo STATIC_URL; ?>/js-admin/plugins/tables/jquery.dataTables.js"></script>
<script type="text/javascript" src="<?php echo STATIC_URL; ?>/js-admin/plugins/tables/jquery.sortable.js"></script>
<script type="text/javascript" src="<?php echo STATIC_URL; ?>/js-admin/plugins/tables/jquery.resizable.js"></script>

<script type="text/javascript" src="<?php echo STATIC_URL; ?>/js-admin/plugins/forms/autogrowtextarea.js"></script>
<script type="text/javascript" src="<?php echo STATIC_URL; ?>/js-admin/plugins/forms/jquery.uniform.js"></script>
<script type="text/javascript" src="<?php echo STATIC_URL; ?>/js-admin/plugins/forms/jquery.inputlimiter.min.js"></script>
<script type="text/javascript" src="<?php echo STATIC_URL; ?>/js-admin/plugins/forms/jquery.tagsinput.min.js"></script>
<script type="text/javascript" src="<?php echo STATIC_URL; ?>/js-admin/plugins/forms/jquery.maskedinput.min.js"></script>
<script type="text/javascript" src="<?php echo STATIC_URL; ?>/js-admin/plugins/forms/jquery.autotab.js"></script>
<script type="text/javascript" src="<?php echo STATIC_URL; ?>/js-admin/plugins/forms/jquery.chosen.min.js"></script>
<script type="text/javascript" src="<?php echo STATIC_URL; ?>/js-admin/plugins/forms/jquery.dualListBox.js"></script>
<script type="text/javascript" src="<?php echo STATIC_URL; ?>/js-admin/plugins/forms/jquery.cleditor.js"></script>
<script type="text/javascript" src="<?php echo STATIC_URL; ?>/js-admin/plugins/forms/jquery.ibutton.js"></script>
<script type="text/javascript" src="<?php echo STATIC_URL; ?>/js-admin/plugins/forms/jquery.validationEngine-en.js"></script>
<script type="text/javascript" src="<?php echo STATIC_URL; ?>/js-admin/plugins/forms/jquery.validationEngine.js"></script>

<script type="text/javascript" src="<?php echo STATIC_URL; ?>/js-admin/plugins/uploader/plupload.js"></script>
<script type="text/javascript" src="<?php echo STATIC_URL; ?>/js-admin/plugins/uploader/plupload.html4.js"></script>
<script type="text/javascript" src="<?php echo STATIC_URL; ?>/js-admin/plugins/uploader/plupload.html5.js"></script>
<script type="text/javascript" src="<?php echo STATIC_URL; ?>/js-admin/plugins/uploader/jquery.plupload.queue.js"></script>

<script type="text/javascript" src="<?php echo STATIC_URL; ?>/js-admin/plugins/wizards/jquery.form.wizard.js"></script>
<script type="text/javascript" src="<?php echo STATIC_URL; ?>/js-admin/plugins/wizards/jquery.validate.js"></script>
<script type="text/javascript" src="<?php echo STATIC_URL; ?>/js-admin/plugins/wizards/jquery.form.js"></script>

<script type="text/javascript" src="<?php echo STATIC_URL; ?>/js-admin/plugins/ui/jquery.collapsible.min.js"></script>
<script type="text/javascript" src="<?php echo STATIC_URL; ?>/js-admin/plugins/ui/jquery.breadcrumbs.js"></script>
<script type="text/javascript" src="<?php echo STATIC_URL; ?>/js-admin/plugins/ui/jquery.tipsy.js"></script>
<script type="text/javascript" src="<?php echo STATIC_URL; ?>/js-admin/plugins/ui/jquery.progress.js"></script>
<script type="text/javascript" src="<?php echo STATIC_URL; ?>/js-admin/plugins/ui/jquery.timeentry.min.js"></script>
<script type="text/javascript" src="<?php echo STATIC_URL; ?>/js-admin/plugins/ui/jquery.colorpicker.js"></script>
<script type="text/javascript" src="<?php echo STATIC_URL; ?>/js-admin/plugins/ui/jquery.jgrowl.js"></script>
<script type="text/javascript" src="<?php echo STATIC_URL; ?>/js-admin/plugins/ui/jquery.fancybox.js"></script>
<script type="text/javascript" src="<?php echo STATIC_URL; ?>/js-admin/plugins/ui/jquery.fileTree.js"></script>
<script type="text/javascript" src="<?php echo STATIC_URL; ?>/js-admin/plugins/ui/jquery.sourcerer.js"></script>

<script type="text/javascript" src="<?php echo STATIC_URL; ?>/js-admin/plugins/others/jquery.fullcalendar.js"></script>
<script type="text/javascript" src="<?php echo STATIC_URL; ?>/js-admin/plugins/others/jquery.elfinder.js"></script>

<script type="text/javascript" src="<?php echo STATIC_URL; ?>/js-admin/plugins/ui/jquery.easytabs.min.js"></script>
<script type="text/javascript" src="<?php echo STATIC_URL; ?>/js-admin/files/bootstrap.js"></script>
<script type="text/javascript" src="<?php echo STATIC_URL; ?>/js-admin/files/functions.js"></script>



</head>

<body>

<!-- Top line begins -->
<div id="top">
    <div class="wrapper">
        <a href="index.html" title="" class="logo"><img src="<?php echo STATIC_ADMIN_IMG; ?>/logo.png" alt="" /></a>
        
        <!-- Right top nav -->
        <div class="topNav">
            <ul class="userNav">
                <li><a title="" class="search"></a></li>
                <li><a href="#" title="" class="screen"></a></li>
                <li><a href="#" title="" class="settings"></a></li>
                <li><a href="#" title="" class="logout"></a></li>
                <li class="showTabletP"><a href="#" title="" class="sidebar"></a></li>
            </ul>
            <a title="" class="iButton"></a>
            <a title="" class="iTop"></a>
            <div class="topSearch">
                <div class="topDropArrow"></div>
                <form action="">
                    <input type="text" placeholder="search..." name="topSearch" />
                    <input type="submit" value="" />
                </form>
            </div>
        </div>
        
        <!-- Responsive nav -->
        <ul class="altMenu">
            <li><a href="index.html" title="">Home</a></li>
            <li><a href="ui.html" title="" class="exp" id="current">UI elements</a>
                <ul>
                    <li><a href="ui.html">General elements</a></li>
                    <li><a href="ui_icons.html">Icons</a></li>
                    <li><a href="ui_buttons.html">Button sets</a></li>
                    <li><a href="ui_grid.html" class="active">Grid</a></li>
                    <li><a href="ui_custom.html">Custom elements</a></li>
                    <li><a href="ui_experimental.html">Experimental</a></li>
                </ul>
            </li>
            <li><a href="forms.html" title="" class="exp">Forms stuff</a>
                <ul>
                    <li><a href="forms.html">Inputs &amp; elements</a></li>
                    <li><a href="form_validation.html">Validation</a></li>
                    <li><a href="form_editor.html">File uploads &amp; editor</a></li>
                    <li><a href="form_wizards.html">Form wizards</a></li>
                </ul>
            </li>
            <li><a href="messages.html" title="">Messages</a></li>
            <li><a href="statistics.html" title="">Statistics</a></li>
            <li><a href="tables.html" title="" class="exp">Tables</a>
                <ul>
                    <li><a href="tables.html">Standard tables</a></li>
                    <li><a href="tables_dynamic.html">Dynamic tables</a></li>
                    <li><a href="tables_control.html">Tables with control</a></li>
                    <li><a href="tables_sortable.html">Sortable &amp; resizable</a></li>
                </ul>
            </li>
            <li><a href="other_calendar.html" title="" class="exp">Other pages</a>
                <ul>
                    <li><a href="other_calendar.html">Calendar</a></li>
                    <li><a href="other_gallery.html">Images gallery</a></li>
                    <li><a href="other_file_manager.html">File manager</a></li>
                    <li><a href="other_404.html">Sample error page</a></li>
                    <li><a href="other_typography.html">Typography</a></li>
                </ul>
            </li>
        </ul>
        <div class="clear"></div>
    </div>
</div>
<!-- Top line ends -->


<!-- Sidebar begins -->
<div id="sidebar">
    <div class="mainNav">                
        <!-- Responsive nav -->
        <div class="altNav">
            <div class="userSearch">
                <form action="">
                    <input type="text" placeholder="search..." name="userSearch" />
                    <input type="submit" value="" />
                </form>
            </div>
            
            <!-- User nav -->
            <ul class="userNav">
                <li><a href="#" title="" class="profile"></a></li>
                <li><a href="#" title="" class="messages"></a></li>
                <li><a href="#" title="" class="settings"></a></li>
                <li><a href="#" title="" class="logout"></a></li>
            </ul>
        </div>
        
        <!-- Main nav -->
        <ul class="nav">
            <?php foreach($this->menu as $index =>$value):
                if($index!='0'):?>
            <li><a href="<?php echo $value['url']?>" 
                   title="<?php echo $value['titulo']?>" 
                   class="active">
                    <img src="<?php echo STATIC_ADMIN_IMG.$value['img']; ?>" 
                         alt="<?echo $value['titulo']?>" />
                    <span><?php echo $value['titulo']?></span>
                </a>
            </li>           
                <?php else: 
                    $each = each($value)?>
            <li><a href="<?php echo $each[1]['url']?>" 
                   title="<?php echo $each[0]?>">
                    <img src="<?php echo STATIC_ADMIN_IMG.$each[1]['img']?>" 
                         alt="<?php echo $each[1]['titulo']?>" />
                    <span><?php echo $each[1]['titulo']?></span>
                </a>
            </li>
                <?php endif;?>
           <? endforeach;?>
        </ul>
    </div>
    
    <!-- Secondary nav -->
    <div class="secNav">
        <div class="secWrapper">                        
            <br>
            <div id="general">                
                <ul class="subNav">
                    <?php foreach($this->submenu as $index=>$value):
                        if($index!='0'):?>
                    <li>
                        <a href="<?php echo $value['url']?>" 
                           title="<?php echo $value['titulo']?>">
                            <span class="icos-cog2"></span>
                            <?php echo $value['titulo']?>
                        </a>
                    </li>
                    <?php else:
                        $each = each($value)?>
                    <li>
                        <a href="<?php echo $each[1]['url']?>" 
                           title="<?php echo $each[1]['titulo']?>" 
                           class="this">
                            <span class="icos-fullscreen"></span>
                            <?php echo $each[1]['titulo']?>
                        </a>
                    </li>
                    <?php endif;
                        endforeach;?>                        
                </ul>
         </div>                                                               
       </div> 
       <div class="clear"></div>
   </div>
</div>
<!-- Sidebar ends -->
    
    
<!-- Content begins -->
<div id="content">               
    <!-- Main content -->
    <div class="wrapper">
   <?php
      echo $this->getMessegerAdmin();
      echo $this->layout()->content 
   ?>
    </div>
    <!-- Main content ends -->
    
</div>
<!-- Content ends -->

</body>
</html>
