<div class="body-content">

    <div class="leftside">
        <div class="topsection">
            <h2 class="section-title">ZONA DE DESCARGAS</h2>
            <div class="subtitle">Descarga</div>
        </div>
        <?php echo $this->navigation()->menu()->renderMenu($this->navigationLeft, array('ulClass' => 'leftmenu')); ?>
    </div>
    <div class="contentside">
      <h1 class="section-title no-bottom">DESCARGAS</h1>
      <div class="subtitle">Compartimos archivos</div>
      <hr class="dotted-long-line">
      <p>Es un hecho establecido hace demasiado tiempo que un lector se distraerá con el contenido del texto de un sitio mientras que mira su diseño. El punto de usar Lorem Ipsum es que tiene una distribución más o menos normal de las letras, al contrario de usar textos como por ejemplo "Contenido aquí, contenido aquí". Estos textos hacen parean evolucionado a través de los años, algunas veces por accidente, otras veces a propósito (por ejemplo insertándole humor y cosas por el estilo).</p>
      <hr class="dotted-long-line">
    </div>
</div>