<div class="contentTop">
    <span class="pageTitle">
        
    </span>
    <div class="clear"></div>
</div>

<?php if (!empty($this->listprojects)): ?>
    <div class="widget check grid9">
        <div class="whead">
            <span class="titleIcon">
                <input type="checkbox" id="titleCheck" name="titleCheck" />
            </span>
            <h6>Gestione sus Noticias</h6>
            <div class="clear"></div>
        </div>
        <table cellpadding="0" cellspacing="0" width="100%" class="tDefault checkAll tMedia" id="checkAll">
            <thead>
                <tr>
                    <td><img src="<?php echo STATIC_ADMIN_IMG; ?>/elements/other/tableArrows.png" alt="" /></td>
                    <td width="130">Nombre</td>
                    <td class="sortCol">
                        <div>Descripción<span></span></div>
                    </td>
                    <td width="130" class="sortCol"><div>Fecha<span></span></div></td>                        
                    <td width="100">Acciones</td>
                </tr>
            </thead>
            <tfoot>
                <tr>
                    <td colspan="5">
                        <div class="itemActions">
                            <label>Seleccion:</label>
                            <select>
                                <option value="">Select action...</option>
                                <option value="Edit">Editar</option>
                                <option value="Delete">Borrar</option>
                                <option value="Move">Desactivar</option>
                            </select>
                        </div>
                        <div class="tPages">
                            <!--                                <ul class="pages">
                                                                <li class="prev"><a href="#" title=""><span class="icon-arrow-14"></span></a></li>
                                                                <li><a href="#" title="" class="active">1</a></li>
                                                                <li><a href="#" title="">2</a></li>
                                                                <li><a href="#" title="">3</a></li>
                                                                <li><a href="#" title="">4</a></li>
                                                                <li>...</li>
                                                                <li><a href="#" title="">20</a></li>
                                                                <li class="next"><a href="#" title=""><span class="icon-arrow-17"></span></a></li>
                                                            </ul>-->
                        </div>
                    </td>
                </tr>
            </tfoot>
            <tbody>
                <?php foreach ($this->listprojects as
                        $index): ?>
                    <tr>
                        <td><input type="checkbox" name="checkRow" /></td>
                        <td>                   
        <?php echo $index['proyectos_nombre'] ?>
                        </td>
                        <td class="textL">
        <?php echo substr($index['proyectos_descripcion'],
            0, 60) . '....' ?>
                        </td>
                        <td><?php echo $index['fecha_creacion'] ?></td>                            
                        <td class="tableActs">
                            <a href="/admin/home/delete-banner/id<?php echo $index['proyectos_id'] ?>" 
                               class="tablectrl_small bDefault tipS" 
                               title="Borrar">
                                <span class="iconb" data-icon="&#xe136;"></span></a>                                
                        </td>
                    </tr>
    <?php endforeach ?>
            </tbody>
        </table>
    </div>
    </div>
<?php endif; ?>
<div id="formDialog" class="dialog" title="Dialog with form elements">
    <form action="">
        <label>Text field:</label>
        <input type="text" name="sampleInput" class="clear" placeholder="Enter something" />
        <div class="divider"><span></span></div>
        <div class="dialogSelect m10">
            <label>Select:</label>
            <select name="select2" >
                <option value="opt1">Usual select box</option>
                <option value="opt2">Option 2</option>
                <option value="opt3">Option 3</option>
                <option value="opt4">Option 4</option>
                <option value="opt5">Option 5</option>
                <option value="opt6">Option 6</option>
                <option value="opt7">Option 7</option>
                <option value="opt8">Option 8</option>
            </select>
        </div>
        <div class="divider"><span></span></div>
        <label>Textarea:</label>
        <textarea rows="8" cols="" name="textarea" class="auto" placeholder="This textarea is elastic"></textarea>
        <div>
            <span class="floatL"><input type="radio" name="dialogRadio" /><label>Radio</label></span>
            <span class="floatR"><input type="checkbox" class="check" name="dialogCheck" checked="checked" /><label>Checkbox</label></span>
            <span class="clear"></span>
        </div>
    </form>
</div>