
<div class="right-zone">
    <div class="section-noticias">
        <h1 class="section-title">Noticias</h1>
        <?php foreach ($this->noticias as $index): ?>
            <div class="bloque-noticias">
                <div class="bloque-noticias-title"><a href="#"><?php echo $index['noticias_titulo'] ?></a></div>
                <div class="bloque-noticias-body">
                    <div class="bloque-noticias-field-image"><img src="<?php echo DINAMIC_URL; ?>/noticias/<?php echo $index['noticias_imagen']; ?>"></div>
                    <div class="bloque-noticias-field-teaser"><?php echo $index['noticias_descripcion_corta']; ?></div>
                    <a href="<?php echo SITE_URL ?>noticias/<?php echo $index['noticias_slug']; ?>" class="bloque-noticias-field-morelink">Leer mas</a>
                </div>
            </div>
        <?php endforeach; ?>   
    </div>
    <div class="section-colabora">
        <h1 class="section-title">Colabora</h1>


        <div class="sectionblock left-block">
            <div class="field-image">
                <img alt="Colabora" src="images/section-colabora-img.jpg">
            </div><div class="bloque-info-colabora">
                <div class="pre-title">PARTICIPA</div>
                <div class="title">Iniciativas Solidarias</div>
                <div class="descripcion">Todos podemos actuar contra la pobreza. Podemos organizar un partido, una cena solidaria o un mercadillo.¿Tienes una idea?</div>
                <a href="#" class="morelink">Cuéntanosla!</a>
            </div></div>

        <div class="sectionblock right-block">
            <div class="field-image">
                <img src="images/section-colabora-img.jpg" alt="Colabora">
            </div><div class="bloque-info-colabora">
                <div class="pre-title">PARTICIPA</div>
                <div class="title">Iniciativas Solidarias</div>
                <div class="descripcion">Todos podemos actuar contra la pobreza. Podemos organizar un partido, una cena solidaria o un mercadillo.¿Tienes una idea?</div>
                <a class="morelink" href="#">Cuéntanosla!</a>
            </div></div>
    </div>
</div>
<div class="left-zone">
    

    <?php foreach ($this->proyectosHome as $valueIndex => $index): ?>
        <?php if ($valueIndex == 0) { ?>
            <div class="bloque-generico">
                <div class="bloque-generico-title"><a href="#"><?php echo $index['proyectos_nombre']; ?></a></div>
                <div class="bloque-generico-body">
                    <?php $imagenesProyecto = explode('|', $index['imagen']); ?>
                    <div class="bloque-generico-field-image"><img src="<?php echo DINAMIC_URL; ?>/proyectos/imagen/<?php echo $imagenesProyecto[0]; ?>"></div>
                    <div class="bloque-generico-field-teaser"><?php echo $index['proyectos_descripcion_corta'] ?></div>
                    <a href="<?php echo SITE_URL ?>proyecto/<?php echo $index['proyectos_slug']; ?>" class="bloque-generico-field-morelink">Leer mas</a>
                </div>
            </div>
        <?php } else { ?>

            <div class="bloque-generico bloque-ultimoproyecto">
                <div class="bloque-generico-title"><a href="#"><?php echo $index['proyectos_nombre']; ?></a></div>
                <div class="bloque-generico-body">
                    <div class="leftside">
                        <div class="texto">

                        </div> 
                        <?php $imagenesProyecto = explode('|', $index['imagen']); ?>
                        <div class="block-images">
                            <?php
                            foreach ($imagenesProyecto as $indexImagen => $valueImagen):
                                if ($indexImagen > 3)
                                    break;
                                ?>
                                <img width="56" height="56" src="<?php echo DINAMIC_URL; ?>/proyectos/imagen/<?php echo $valueImagen; ?>">
        <?php endforeach; ?>

                        </div>
                    </div>
                    <div class="rightside">
                        <div class="bloque-generico-field-image"><img style="width: 204px; height: 77px;" src="<?php echo DINAMIC_URL; ?>/proyectos/imagen/<?php echo $imagenesProyecto[0]; ?>"></div>
                        <div class="bloque-generico-field-teaser"><?php echo $index['proyectos_descripcion_corta'] ?></div>
                        <a class="bloque-generico-field-morelink" href="<?php echo SITE_URL ?>proyecto/<?php echo $index['proyectos_slug']; ?>">Leer mas</a>
                    </div>
                </div>
            </div>
    <?php } ?>
<?php endforeach; ?>

</div>
