<div class="body-content">
    <div class="leftside">
      <div class="topsection">
        <h2 class="section-title">SALA DE PRENSA</h2>
        <div class="subtitle">Prensa</div>
      </div>
      <ul class="leftmenu">
        <li><a href="noticias.html" class="active">Noticias</a></li>
        <li><a href="dossier-de-prensa.html">Dossier de prensa</a></li>
      </ul>
    </div>
    <div class="contentside">
      <h1 class="section-title no-bottom">NOTICIAS</h1>
      <div class="subtitle">Información dirigida a los medios</div>
      <hr class="dotted-long-line">
      <div class="noticias-gallery">
        <div class="noticias-column nc-first">
          <div class="noticia-bloque">
            <h3 class="titulo">Titulo</h3>
            <div class="subtitulo">Subtitulo</div>
            <div class="image-field"><img width="136" height="67" src="images/picture01.jpg" alt="Imagen 1"></div>
            <div class="noticia-descripcion">Es un hecho establecido hace demasiado tiempo que un lector se distraerá con el contenido del texto de un sitio mientras</div>
            <a href="#">Leer más</a> </div>
          <div class="noticia-bloque">
            <h3 class="titulo">Titulo</h3>
            <div class="subtitulo">Subtitulo</div>
            <div class="image-field"><img width="136" height="67" src="images/picture01.jpg" alt="Imagen 1"></div>
            <div class="noticia-descripcion">Es un hecho establecido hace demasiado tiempo que un lector se distraerá con el contenido del texto de un sitio mientras</div>
            <a href="#">Leer más</a> </div>
        </div>
        <div class="noticias-column">
          <div class="noticia-bloque">
            <h3 class="titulo">Titulo</h3>
            <div class="subtitulo">Subtitulo</div>
            <div class="image-field"><img width="136" height="67" src="images/picture01.jpg" alt="Imagen 1"></div>
            <div class="noticia-descripcion">Es un hecho establecido hace demasiado tiempo que un lector se distraerá con el contenido del texto de un sitio mientras</div>
            <a href="#">Leer más</a> </div>
          <div class="noticia-bloque">
            <h3 class="titulo">Titulo</h3>
            <div class="subtitulo">Subtitulo</div>
            <div class="image-field"><img width="136" height="67" src="images/picture01.jpg" alt="Imagen 1"></div>
            <div class="noticia-descripcion">Es un hecho establecido hace demasiado tiempo que un lector se distraerá con el contenido del texto de un sitio mientras</div>
            <a href="#">Leer más</a> </div>
        </div>
        <div class="noticias-column nc-last">
          <div class="noticia-bloque">
            <h3 class="titulo">Titulo</h3>
            <div class="subtitulo">Subtitulo</div>
            <div class="image-field"><img width="136" height="67" src="images/picture01.jpg" alt="Imagen 1"></div>
            <div class="noticia-descripcion">Es un hecho establecido hace demasiado tiempo que un lector se distraerá con el contenido del texto de un sitio mientras</div>
            <a href="#">Leer más</a> </div>
          <div class="noticia-bloque">
            <h3 class="titulo">Titulo</h3>
            <div class="subtitulo">Subtitulo</div>
            <div class="image-field"><img width="136" height="67" src="images/picture01.jpg" alt="Imagen 1"></div>
            <div class="noticia-descripcion">Es un hecho establecido hace demasiado tiempo que un lector se distraerá con el contenido del texto de un sitio mientras</div>
            <a href="#">Leer más</a> </div>
        </div>
      </div>
      <hr class="dotted-long-line">
    </div>
  </div>