<div class="body-content">

    <div class="leftside">
        <div class="topsection">
            <h2 class="section-title">¿QUIENES SOMOS?</h2>
            <div class="subtitle">Acerca de nosotros</div>
        </div>
        <?php echo $this->navigation()->menu()->renderMenu($this->navigationLeft, array('ulClass' => 'leftmenu')); ?>
        <!--<ul class="leftmenu">
                <li><a href="/quienes-somos/historia">La Historia</a></li>
                <li><a href="visionmision.html">Mision y vision</a></li>
                <li><a href="principios-actuacion.html">Principios de actuacion</a></li>
                <li><a href="memorias.html">Memorias</a></li>
                <li><a href="nuestro-equipo.html">Nuestro equipo</a></li>
        </ul> -->

    </div>
    <div class="contentside">
        <h1 class="section-title">HISTORIA</h1>
        <div class="bloque-content">

            <div class="bloque-text">
                <p>L Lorem ipsum Lorem ipsum Lorem ipsumLorem ipsum Lorem ipsum Lorem ipsumLorem ipsumLorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum orem ipsum L Lorem ipsum Lorem ipsum Lorem ipsumLorem ipsum Lorem ipsum Lorem ipsumLorem ipsumLorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum orem ipsum
                </p>
                <div class="bloque-doble-imagen">
                    <img width="135" alt="Imagen 1" src="<?php echo STATIC_URL; ?>/images/picture01.jpg">
                    <img width="135" alt="Imagen 1" src="<?php echo STATIC_URL; ?>/images/picture01.jpg">
                </div>

            </div>

            <div class="bloque-imagen">
                <img alt="Imagen 1" src="<?php echo STATIC_URL; ?>/images/picture01.jpg">
            </div>
        </div>

        <div class="bloque-content">

            <div class="bloque-text">
                L Lorem ipsum Lorem ipsum Lorem ipsumLorem ipsum Lorem ipsum Lorem ipsumLorem ipsumLorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum orem ipsum
            </div>
            <div class="bloque-imagen">
                <img src="<?php echo STATIC_URL; ?>/images/picture01.jpg" alt="Imagen 1">
            </div>
        </div>

        <div class="compartir">
            <span class="compartir-label">Compartir</span>
            <a href=""><img src="<?php echo STATIC_URL; ?>/images/mini-facebook.jpg"></a>
            <a href=""><img src="<?php echo STATIC_URL; ?>/images/mini-twitter.jpg"></a>
            <a href="#"><img src="<?php echo STATIC_URL; ?>/images/mini-icon3.jpg"></a>
            <a href="#"><img src="<?php echo STATIC_URL; ?>/images/mini-mail.jpg"></a>
        </div>

    </div>
</div>