<div class="body-content">

    <div class="leftside">
        <div class="topsection">
            <h2 class="section-title">¿QUIENES SOMOS?</h2>
            <div class="subtitle">Acerca de nosotros</div>
        </div>
        <?php echo $this->navigation()->menu()->renderMenu($this->navigationLeft, array('ulClass' => 'leftmenu')); ?>
    </div>
    <div class="contentside">
<h1 class="section-title">Bienvenidos a la sección memorias</h1>


<p>Es un hecho establecido hace demasiado tiempo que un lector se distraerá con el contenido del texto de un sitio mientras que mira su diseño. El punto de usar Lorem Ipsum es que tiene una distribución más o menos normal de las letras, al contrario de usar textos como por ejemplo "Contenido aquí, contenido aquí". Estos textos hacen parean evolucionado a través de los años, algunas veces por accidente, otras veces a propósito (por ejemplo insertándole humor y cosas por el estilo).</p>
<div class="memorias-gallery">
    <?php $arrayClass = array(
        'memoriabox leftcolumn',
        'memoriabox centralcolumn',
        'memoriabox rightcolumn'
        ); ?>
    <?php foreach($this->listingMemorias as $index=>$value): 
        $indexArray = $index+1;
        if($index%3==0){
            $indexArray=0;
        }elseif($index%2==0){
            $indexArray=2;
        }else{
            $indexArray=1;
        }
        
        ?>
<div class="<?php echo $arrayClass[$indexArray]; ?>">
<div class="label"><?php echo $value['memorias_nombre']; ?></div>
<a href="#"><img width="128" height="112" src="<?php echo DINAMIC_URL ?>/memorias/<?php echo $value['memorias_imagen']; ?>"></a>
</div>
    <?php endforeach; ?>

<!--<div class="memoriabox centralcolumn">
<div class="label">MEMORIA</div>
<a href="#"><img src="<?php echo STATIC_URL; ?>/images/imagen01.jpg"></a>
</div>

<div class="memoriabox rightcolumn">
<div class="label">MEMORIA</div>
<a href="#"><img src="<?php echo STATIC_URL; ?>/images/imagen01.jpg"></a>
</div>

<div class="memoriabox leftcolumn">
<div class="label">MEMORIA</div>
<a href="#"><img src="<?php echo STATIC_URL; ?>/images/imagen01.jpg"></a>
</div>

<div class="memoriabox centralcolumn">
<div class="label">MEMORIA</div>
<a href="#"><img src="<?php echo STATIC_URL; ?>/images/imagen01.jpg"></a>
</div>

<div class="memoriabox rightcolumn">
<div class="label">MEMORIA</div>
<a href="#"><img src="<?php echo STATIC_URL; ?>/images/imagen01.jpg"></a>
</div>-->

</div>

<div class="compartir">
	<span class="compartir-label">Compartir</span>
	<a href=""><img src="<?php echo STATIC_URL; ?>/images/mini-facebook.jpg"></a>
	<a href=""><img src="<?php echo STATIC_URL; ?>/images/mini-twitter.jpg"></a>
	<a href="#"><img src="<?php echo STATIC_URL; ?>/images/mini-icon3.jpg"></a>
	<a href="#"><img src="<?php echo STATIC_URL; ?>/images/mini-mail.jpg"></a>
</div>

</div>
</div>