<div class="body-content">

    <div class="leftside">
        <div class="topsection">
            <h2 class="section-title">¿QUIENES SOMOS?</h2>
            <div class="subtitle">Acerca de nosotros</div>
        </div>
        <?php echo $this->navigation()->menu()->renderMenu($this->navigationLeft, array('ulClass' => 'leftmenu')); ?>
    </div>
    <div class="contentside">
<h1 class="section-title">Nuestro equipo</h1>
<span class="subtitle">Bienvenidos a la sección de nuestro equipo, aquí podra encontrar información de nuestro personal continuo</span>

<p>Es un hecho establecido hace demasiado tiempo que un lector se distraerá con el contenido del texto de un sitio mientras que mira su diseño. El punto de usar Lorem Ipsum es que tiene una distribución más o menos normal de las letras, al contrario de usar textos como por ejemplo "Contenido aquí, contenido aquí". Estos textos hacen parean evolucionado a través de los años, algunas veces por accidente, otras veces a propósito (por ejemplo insertándole humor y cosas por el estilo).</p>
<div class="personal-gallery">
	<h3 class="zone-title">Personal continuo</h3>
</div>

<?php foreach($this->listingMiembros as $index): ?>
<div class="personal-gallery">
<div class="personal-box">
    <div class="profile-picture"><img width="44" height="53" src="<?php echo DINAMIC_URL; ?>/mienbros/<?php echo $index['miembros_imagen'] ?>"></div>
<div class="profile-name"><?php echo $index['miembros_nombre'].' '.$index['miembros_apellidos'] ?></div>
</div>
</div>
<?php endforeach;?>




<div class="compartir">
	<span class="compartir-label">Compartir</span>
	<a href=""><img src="<?php echo STATIC_URL; ?>/images/mini-facebook.jpg"></a>
	<a href=""><img src="<?php echo STATIC_URL; ?>/images/mini-twitter.jpg"></a>
	<a href="#"><img src="<?php echo STATIC_URL; ?>/images/mini-icon3.jpg"></a>
	<a href="#"><img src="<?php echo STATIC_URL; ?>/images/mini-mail.jpg"></a>
</div>

</div>
</div>