<div class="body-content">

    <div class="leftside">
        <div class="topsection">
            <h2 class="section-title">¿QUIENES SOMOS?</h2>
            <div class="subtitle">Acerca de nosotros</div>
        </div>
        <?php echo $this->navigation()->menu()->renderMenu($this->navigationLeft, array('ulClass' => 'leftmenu')); ?>
    </div>
    <div class="contentside">
<h1 class="section-title">PRINCIPIOS DE ACTUACION</h1>
<div class="bloque-content">

<div class="leftzone">
<div class="bloque-text"><div class="subtitle">Principio1:</div>
L Lorem ipsum Lorem ipsum Lorem ipsumLorem ipsum Lorem ipsum Lorem ipsumLorem ipsumLorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum orem ipsum
</div>

<div class="bloque-text"><div class="subtitle">Principio2:</div>
L Lorem ipsum Lorem ipsum Lorem ipsumLorem ipsum Lorem ipsum Lorem ipsumLorem ipsumLorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum orem ipsum
</div>


<div class="bloque-text"><div class="subtitle">Principio3:</div>
L Lorem ipsum Lorem ipsum Lorem ipsumLorem ipsum Lorem ipsum Lorem ipsumLorem ipsumLorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum orem ipsum
</div>

<div class="bloque-text"><div class="subtitle">Principio 4:</div>
L Lorem ipsum Lorem ipsum Lorem ipsumLorem ipsum Lorem ipsum Lorem ipsumLorem ipsumLorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum orem ipsum
</div>
</div>

<div class="bloque-images">



<div class="bloque-imagen">
<img src="<?php echo STATIC_URL; ?>/images/picture01.jpg" alt="Imagen 1">
</div>
<div class="bloque-imagen">
<img src="<?php echo STATIC_URL; ?>/images/picture01.jpg" alt="Imagen 1">
</div>
</div>

</div>

<div class="bloque-content">

<div class="bloque-text">
L Lorem ipsum Lorem ipsum Lorem ipsumLorem ipsum Lorem ipsum Lorem ipsumLorem ipsumLorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum orem ipsum
</div>

</div>

<div class="compartir">
	<span class="compartir-label">Compartir</span>
	<a href=""><img src="<?php echo STATIC_URL; ?>/images/mini-facebook.jpg"></a>
	<a href=""><img src="<?php echo STATIC_URL; ?>/images/mini-twitter.jpg"></a>
	<a href="#"><img src="<?php echo STATIC_URL; ?>/images/mini-icon3.jpg"></a>
	<a href="#"><img src="<?php echo STATIC_URL; ?>/images/mini-mail.jpg"></a>
</div>

</div>
</div>