<div class="body-content">

    <div class="leftside">
        <div class="topsection">
            <h2 class="section-title">LA COMPAÑIA</h2>
            <div class="subtitle">Acerca de nosotros</div>
        </div>
        <?php echo $this->navigation()->menu()->renderMenu($this->navigationLeft, array('ulClass' => 'leftmenu')); ?>
    </div>
    <div class="contentside">
        <h1 class="section-title">MISION Y VISION</h1>
        <div class="bloque-content">
            <h2 class="bloque-title">Mision</h2>
            <div class="bloque-text">
                L Lorem ipsum Lorem ipsum Lorem ipsumLorem ipsum Lorem ipsum Lorem ipsumLorem ipsumLorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum orem ipsum L Lorem ipsum Lorem ipsum Lorem ipsumLorem ipsum Lorem ipsum Lorem ipsumLorem ipsumLorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum orem ipsum
            </div>
            <div class="bloque-imagen">
                <img src="images/picture01.jpg" alt="Imagen 1">
            </div>
        </div>

        <div class="bloque-content">
            <h2 class="bloque-title">Vision</h2>
            <div class="bloque-text">
                L Lorem ipsum Lorem ipsum Lorem ipsumLorem ipsum Lorem ipsum Lorem ipsumLorem ipsumLorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum orem ipsum
            </div>
            <div class="bloque-imagen">
                <img src="images/picture01.jpg" alt="Imagen 1">
            </div>
        </div>

        <div class="compartir">
            <span class="compartir-label">Compartir</span>
            <a href=""><img src="images/mini-facebook.jpg"></a>
            <a href=""><img src="images/mini-twitter.jpg"></a>
            <a href="#"><img src="images/mini-icon3.jpg"></a>
            <a href="#"><img src="images/mini-mail.jpg"></a>
        </div>

    </div>
</div>