<form action="" method='post'  enctype="multipart/form-data" name="banner">
<div class="grid3">
    <label>Cargue una imagen :
    </label> 
</div>
<div class="grid3">
    <?php echo $this->element->titulo; ?>

</div>        
<div class="grid3">
    <?php echo $this->element->imagen; ?>            
</div>                

<div class="clear"></div>
    <input type="submit" value="Enviar" id="Enviar" name="Enviar">
</form>