<div class="body-content">

<div class="leftside">
<ul class="leftmenu">
<li><a href="">Item1</a></li>
</ul>
</div>
<div class="contentside">
<h1 class="section-title">MISION Y VISION</h1>
<div class="bloque-content">
<h2 class="bloque-title">MISION</h2>
<div class="bloque-text">
L Lorem ipsum Lorem ipsum Lorem ipsumLorem ipsum Lorem ipsum Lorem ipsumLorem ipsumLorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum orem ipsum
</div>
<div class="bloque-imagen">
<img src="images/logo.jpg">
</div>
</div>

<div class="bloque-content">
<h2 class="bloque-title">MISION</h2>
<div class="bloque-text">
L Lorem ipsum Lorem ipsum Lorem ipsumLorem ipsum Lorem ipsum Lorem ipsumLorem ipsumLorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum orem ipsum
</div>
<div class="bloque-imagen">
<img src="images/logo.jpg">
</div>
</div>
</div>
</div>