<div class="nNote"><?php foreach($this->message as $index):  
echo '<p>'.$index.'</p>';
 endforeach;  ?></div>
<a href="/admin/wallpaper/insert">Nuevo Registro</a>
<table>
    <tr> 
        <td>nombre </td>
        <td>descripcion</td>
        <td>imagen</td>
        <td>estado</td>
        <td>orden</td>
        <td>Opciones</td>
    </tr>
    
 <?php 
 $arrayEstado = array('no publico', 'publico' );
 $arrayLinkPublicar = array(
     array('link'=>'/admin/wallpaper/publicar/id/','label'=>'publicar'), 
     array('link'=>'/admin/wallpaper/despublicar/id/','label'=>'despublicar'), 
     );
 foreach($this->listingWallpaper as $index): ?>
    <tr> 
        <td><?php echo $index['wallpaper_nombre']; ?></td>
        <td><?php echo $index['wallpaper_descripcion']; ?></td>
        <td><?php echo $index['wallpaper_imagen']; ?></td>
        <td><?php echo $arrayEstado[$index['wallpaper_publico']]; ?></td>
        <td><?php echo $index['wallpaper_orden']; ?></td>
        <td>
            <a href="/admin/wallpaper/edit/id/<?php echo $index['wallpaper_id']; ?>" > [Editar]</a>
            <a href="<?php echo $arrayLinkPublicar[$index['wallpaper_publico']]['link'].$index['wallpaper_id']; ?>">[<?php echo $arrayLinkPublicar[$index['wallpaper_publico']]['label']; ?>]</a>
            <a href="/admin/wallpaper/uporder/id/<?php echo $index['wallpaper_id']; ?>" > [Subir orden]</a>
            <a href="/admin/wallpaper/lowerorder/id/<?php echo $index['wallpaper_id']; ?>" > [Bajar orden]</a>
        </td>
    </tr>

<?php endforeach; ?>
</table>