<div class="body-content">
    <div class="leftside">
      <div class="topsection">
        <h2 class="section-title">EMPIEZA A COLABORAR</h2>
        <div class="subtitle">Colabora</div>
      </div>
      <ul id="nav" class="leftmenu">
        <li class="parent"><a href="#">Padrinos</a>
          <ul>
            <li><a href="padrinos-descripcion.html">Descripción</a></li>
            <li><a href="padrinos-quiero-apadrinar.html">Quiero apadrinar</a></li>
            <li><a href="padrinos-preguntas-frecuentes.html">Preguntas Frecuentes</a></li>
          </ul>
        </li>
        <li class="parent"><a href="#">Socio colaborador</a>
        <ul>
          <li><a href="sc-descripcion.html">Descripción</a></li>
            <li><a href="sc-ejemplo-de-inversion.html">Ejemplo de inversión</a></li>
            <li><a href="sc-quiero-ser-socio-colaborador.html">Quiero ser socio colaborador</a></li>
            <li><a href="sc-preguntas-frecuentes.html">Preguntas frecuentes</a></li>
        </ul>
        </li>
        <li><a href="donantes.html">Donantes</a></li>
        <li><a href="legado-solidario.html">Legado solidario</a></li>
        <li class="parent"><a href="#">Acción social empresarial</a>
          <ul>
            <li><a href="ase-tipos-de-colaboracion.html">Tipos de colaboración</a></li>
              <li><a href="ase-incentivos-de-colaboracion.html">Incentivos de colaboración</a></li>
              <li><a href="ase-nuestros-colaboradores.html">Nuestros colaboradores</a></li>
              <li><a href="ase-preguntas-frecuentes.html">Preguntas frecuentes</a></li>
          </ul>
        </li>
      </ul>
    </div>
    <div class="contentside">
      <h1 class="section-title clean-title">COLABORA</h1>
      <hr class="dotted-long-line">
      <p>Es un hecho establecido hace demasiado tiempo que un lector se distraerá con el contenido del texto de un sitio mientras que mira su diseño. El punto de usar Lorem Ipsum es que tiene una distribución más o menos normal de las letras, al contrario de usar textos como por ejemplo "Contenido aquí, contenido aquí". Estos textos hacen parecerlo un español que se puede leer. Muchos paquetes de autoedición y editores de páginas web usan el Lorem Ipsum como su texto por defecto, y al hacer una búsqueda de "Lorem Ipsum" va a dar por resultado muchos sitios web que usan este texto si se encuentran en estado de desarrollo. Muchas versiones han evolucionado a través de los años, algunas veces por accidente, otras veces a propósito (por ejemplo insertándole humor y cosas por el estilo).</p>
      <div class="small-gallery">
        <div class="picturebox">
          <div class="label">PADRINOS</div>
          <a href="#"><img src="images/colabora1.jpg"></a> </div>
        <div class="picturebox">
          <div class="label">SOCIO COLABORADOR</div>
          <a href="#"><img src="images/colabora2.jpg"></a> </div>
        <div class="picturebox">
          <div class="label">DONANTES</div>
          <a href="#"><img src="images/colabora3.jpg"></a> </div>
        <div class="picturebox">
          <div class="label">LEGADO SOLIDARIO</div>
          <a href="#"><img src="images/colabora4.jpg"></a> </div>
        <div class="picturebox">
          <div class="label">ACCIÓN SOCIAL EMPRESARIAL</div>
          <a href="#"><img src="images/colabora5.jpg"></a> </div>
      </div>
      <hr class="dotted-long-line">
    </div>
  </div>